---
- name: Create config.json template
  ansible.builtin.template:
    src: templates/config.json.j2
    dest: "{{ orchestrator_config_dir }}/config.json"
    mode: '0644'
    backup: yes

- name: Create systemd service file
  ansible.builtin.template:
    src: templates/orchestrator.service.j2
    dest: /etc/systemd/system/orchestrator.service
    mode: '0644'
    backup: yes

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start orchestrator service
  ansible.builtin.systemd:
    name: orchestrator
    state: started
    enabled: yes
  register: service_start

- name: Show service status
  ansible.builtin.debug:
    msg: "Orchestrator service {{ 'started successfully' if service_start.changed else 'was already running' }}" 